# Generated by Django 2.0.1 on 2020-09-21 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20200920_0346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('change_nfe', 'Usuário pode modificar NF-e'), ('permissao2', 'Permissão 2'), ('permissao3', 'Permissão 3'))},
        ),
    ]
