# Generated by Django 2.0.1 on 2020-09-21 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_auto_20200921_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('change_nfe', 'Usuário pode modificar NF-e'), ('view_dashboard', 'Pode visualizar o Dashboard'), ('permissao3', 'Permissão 3'))},
        ),
    ]
